version: '3.8'

services:
  chatbot-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_CONNECTION=postgresql+psycopg://postgres:postgres@host.docker.internal:5432/app
      - GEMINI_API_KEY=AIzaSyCRPj8jm-JTpNN9jfOkg76au8oppkWi0Ss
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./app:/app
    restart: unless-stopped
