version: "3.9"

services:
  chatbot-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    environment:
      - POSTGRES_CONNECTION=postgresql+psycopg://postgres:postgres@host.docker.internal:5433/app
      - GEMINI_API_KEY=""
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./app:/app/app
    restart: unless-stopped

  web:
    build:
      context: ./Agentic-Chatbot/agentic-chatbot
      dockerfile: Dockerfile
    container_name: agentic-chatbot
    ports:
      - "3000:3000"
    env_file:
      - ./Agentic-Chatbot/agentic-chatbot/.env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY:-AIzaSyBKT6-nzJADAA3sTI7IuwMjjPtqIy5z4TY}
      - GOOGLE_GEMINI_MODEL=${GOOGLE_GEMINI_MODEL:-gemini-2.5-pro}
      - GOOGLE_GEMINI_FLASH_MODEL=${GOOGLE_GEMINI_FLASH_MODEL:-gemini-2.5-flash}
      - CHATBOT_RESPONSE_TIMEOUT_MS=${CHATBOT_RESPONSE_TIMEOUT_MS:-30000}
      - THINKING_BUDGET_RETRY=${THINKING_BUDGET_RETRY:-512}
      - THINKING_BUDGET_INTERPRET=${THINKING_BUDGET_INTERPRET:-128}
      - THINKING_BUDGET_EXECUTE=${THINKING_BUDGET_EXECUTE:-512}
      - THINKING_BUDGET_REASON=${THINKING_BUDGET_REASON:-0}
      - MDB_MCP_CONNECTION_STRING=${MDB_MCP_CONNECTION_STRING:-mongodb://localhost:27017/}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
