version: "3.9"

services:
  web:
    build:
      context: ./agentic-chatbot
      dockerfile: Dockerfile
    container_name: agentic-chatbot
    ports:
      - "3000:3000"
    # Load defaults from example env if you copy it to .env
    env_file:
      - ./agentic-chatbot/.env.example
    environment:
      # App env
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}

      # Google AI keys/models (override via real .env or shell)
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY:-your_google_ai_api_key_here}
      - GOOGLE_GEMINI_MODEL=${GOOGLE_GEMINI_MODEL:-gemini-2.5-pro}
      - GOOGLE_GEMINI_FLASH_MODEL=${GOOGLE_GEMINI_FLASH_MODEL:-gemini-2.5-flash}
      - CHATBOT_RESPONSE_TIMEOUT_MS=${CHATBOT_RESPONSE_TIMEOUT_MS:-30000}

      # Thinking budgets (optional)
      - THINKING_BUDGET_RETRY=${THINKING_BUDGET_RETRY:-512}
      - THINKING_BUDGET_INTERPRET=${THINKING_BUDGET_INTERPRET:-128}
      - THINKING_BUDGET_EXECUTE=${THINKING_BUDGET_EXECUTE:-512}
      - THINKING_BUDGET_REASON=${THINKING_BUDGET_REASON:-0}

      # MCP Mongo connection (host network)
      - MDB_MCP_CONNECTION_STRING=${MDB_MCP_CONNECTION_STRING:-mongodb://localhost:27017/}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    restart: unless-stopped